improved error msg when fjconfig not found
git-svn-id: svn+ssh://phab.hepforge.org/source/fastjetsvn/contrib/trunk@281 3dcf5ceb-c996-4387-9042-f4b6870d0cfc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -149,7 +149,11 @@ done
 
 # exit if fastjet-config is not found (bad file name or not in path)
 if ! [ `command -v $fjconfig` ]; then
-    echo $fjconfig" has not been found. Exiting."; exit 1 
+    echo "Error:" $fjconfig" has not been found."
+    echo "       You may explicitly specify the location of fastjet-config "
+    echo "       with the option --fastjet-config=...."
+    echo "Exiting"
+    exit 1 
 fi
 
 # if prefix has not been set explicitly from command line, set it to
